 language: node_js
 node_js:
   - "0.8"

 branches:
  except:
    - /^feature.*$/

 before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g testacular

 script: "./node_modules/.bin/karma start config/testacular.conf.js --single-run"
