language: python
python:
  - "2.7"
node_js:
  - "0.8"
  - "0.10"
services: mongodb
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
    - master
# command to install dependencies with mobyle2.lib on develop
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install python-coveralls"
  - "python setup.py -q install"

# run js part unit tests in before-script
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - cd mobyle/web/webapp
  - npm install
  - grunt karma
  - cd ../../..

# command to run tests
script: nosetests --with-coverage --cover-package=mobyle
after_success:
  - coveralls


