language: python
python:
  - "2.7"
services: mongodb
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies with mobyle2.lib on develop
install:
  - "pip install paste pastedeploy pastescript py-bcrypt mongokit"
  - "pip install 'pyparsing<2.0'"
  - "pip install pyramid pyramid_debugtoolbar waitress pyramid_beaker pymongo pyramid_mailer py-bcrypt pyScss webtest mf pygeoip"
  - "pip install git+https://github.com/bbangert/velruse.git"
  - "pip install git+https://github.com/mobyle2/mobyle2.lib.git@develop#egg=mobyle.lib"
  - "python setup.py -q install"
# command to run tests
script: nosetests


